### ISSUE TITLE
Please release custom alarm naming

### ISSUE THREAD

**Issue by wheresrhys** [ACloudGuru/serverless-plugin-aws-alerts#101]
Hi - it's been a few days since this was merged into master. Would love it if this feature was released. Is there anything blocking it?

**Comment by bulkan** [comment]
I've pushed 1.3.1 to npm last Friday.

https://www.npmjs.com/package/serverless-plugin-aws-alerts

**Comment by bulkan** [comment]
@wheresrhys  I've double checked and 1.3.1 didn't contain the custom alarm naming so I've pushed 1.4.0 which reflects what is available on master.
