### ISSUE TITLE
Dashboard widgets are not populating with data

### ISSUE THREAD

**Issue by justengland** [ACloudGuru/serverless-plugin-aws-alerts#107]
# This is a Bug Report 

## Description
Dashboard are created but they are using invalid metrics.

For bug reports:
* What went wrong?
I added dashboards but the dashboards have the wrong metrics.

* What did you expect should have happened?
The dashboards should be populated with the correct metrics, but no metrics are populated in any of the widgets.
The actual metric detail is this
`Lambda•Invocations•FunctionName: my-function-name`
the expected metric detail is
`Lambda•Invocations•FunctionName: My-Function-Name•Resource:`

For example 

* What was the config you used?
```  
alerts:
    dashboards: true

    topics:
      alarm: ${self:provider.environment.MARBOT_ALERT_ARN}
      insufficientData: ${self:provider.environment.MARBOT_ALERT_ARN}

    definitions:  # these defaults are merged with your definitions
      functionInvocations:
        period: 300 # override period
      functionDuration:
        statistic: Maximum
        threshold: 845

    alarms:
      - functionThrottles
      - functionErrors
      - functionInvocations
      - functionDuration```
* What stacktrace or error message from your provider did you see?
There was no error, so I do not see anything special in the log.

is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by justengland** [comment]
Nobody cares :(

**Comment by bulkan** [comment]
@justengland hi there, thanks for the report.

Can you please change your `topics` to follow [this format](https://github.com/ACloudGuru/serverless-plugin-aws-alerts/blob/master/example/serverless.yml#L25) and see if it works.

>

**Comment by justengland** [comment]
It's probably not going to happen, I tried to follow your process last month. But your team did not seem to care then, so I dont care now.

**Comment by adikari** [comment]
Closing as there is no response from reporter.
