### ISSUE TITLE
what's the latest serverless version that is supported by the plugin?

### ISSUE THREAD

**Issue by AlexSun98** [ACloudGuru/serverless-plugin-aws-alerts#114]
what's the latest serverless version that is supported by the plugin? 

1.63?
1.50?
1.26?

**Comment by clementheliou** [comment]
We are able to make it work with the 1.59 version.
Didn't try it with higher versions.

**Comment by AlexSun98** [comment]
Just a quick update. I've tried serverless V1.80.0 recently. I see the below errors. 

`
Type Error ---------------------------------------------
--
275 |  
276 | TypeError: Cannot convert undefined or null to object
277 | at Function.keys (<anonymous>)
278 | at /codebuild/output/src311476625/src/node_modules/serverless-plugin-aws-alerts/src/index.js:280:18
279 | at Array.forEach (<anonymous>)
280 | at AlertsPlugin.compileAlertTopics (/codebuild/output/src311476625/src/node_modules/serverless-plugin-aws-alerts/src/index.js:276:34)
281 | at AlertsPlugin.compile (/codebuild/output/src311476625/src/node_modules/serverless-plugin-aws-alerts/src/index.js:424:30)
282 | at /codebuild/output/src311476625/src/node_modules/serverless/lib/classes/PluginManager.js:498:55
283 | at tryCatcher (/codebuild/output/src311476625/src/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
284 | at Object.gotValue (/codebuild/output/src311476625/src/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:168:18)
285 | at Object.gotAccum (/codebuild/output/src311476625/src/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:155:25)
286 | at Object.tryCatcher (/codebuild/output/src311476625/src/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
287 | at Promise._settlePromiseFromHandler (/codebuild/output/src311476625/src/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
288 | at Promise._settlePromise (/codebuild/output/src311476625/src/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
289 | at Promise._settlePromise0 (/codebuild/output/src311476625/src/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
290 | at Promise._settlePromises (/codebuild/output/src311476625/src/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
291 | at _drainQueueStep (/codebuild/output/src311476625/src/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)
292 | at _drainQueue (/codebuild/output/src311476625/src/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
293 | at Async._drainQueues (/codebuild/output/src311476625/src/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
294 | at Immediate.Async.drainQueues [as _onImmediate] (/codebuild/output/src311476625/src/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
295 | at processImmediate (internal/timers.js:456:21)
296 |  
297 | For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

`

**Comment by AlexSun98** [comment]
might have sth to do with aws sdk upgrade?

**Comment by clementheliou** [comment]
@AlexSun98 thanks for the update.
I'll take a look at it as soon as possible.

**Comment by thetumper** [comment]
Having a very similar issue:

[sls] Serverless: Validating template...
[sls]   Error --------------------------------------------------
[sls]   Error: The CloudFormation template is invalid: [/Resources/MyFunctionErrorsAlarm/Type/OKActions/1] 'null' values are not allowed in templates

This is at deploy time, despite successfully packaging in local (i.e., "sls package --stage dev").

**Comment by PatrykMilewski** [comment]
It was working fine for us until Serverless@2.4.0, so 2.3.0 is latest working version. Check out #145

**Comment by graemesmithmedkeeper** [comment]
I just installed the plugin with Serverless 2.17.0 and it seems to work from a cursory test. Any update on what's actually supported? I guess I'm not going to use this with my project if people are seeing issues.

**Comment by adikari** [comment]
It should work with serverless version 2.
