### ISSUE TITLE
Is the project DEAD?

### ISSUE THREAD

**Issue by micheleangioni** [ACloudGuru/serverless-plugin-aws-alerts#147]
Hi guys @johncmckim @tdimmig @adikari ,

since this plugin cannot be used with serverless v2, as seen [here](https://github.com/ACloudGuru/serverless-plugin-aws-alerts/issues/145) and [here](https://github.com/ACloudGuru/serverless-plugin-aws-alerts/issues/139), I honestly think you should clearly mark it as deprecated.

Otherwise, is there any support planned to bring new life to it?

Thanks!

**Comment by MatissJanis** [comment]
Are there any alternatives for v2?

**Comment by DVader666** [comment]
Any news on this project and its support for SLS v2+?

**Comment by adikari** [comment]
@micheleangioni currently I am maintaining this on my own time and very limited time to spend on this. Happy for someone to update the package to support v2. I might work on it sometimes this year if I got some spare time.
