### ISSUE TITLE
not able to deploy after putting serverless-plugin-aws-alerts in package.json

### ISSUE THREAD

**Issue by luckynilay** [ACloudGuru/serverless-plugin-aws-alerts#156]
# This is a (Bug Report / Feature Proposal)

## Description

I am facing issue where in deployment stage, error get thrown saying "alarm.reduce is not a function". Below is my serverless and plugin version :

serverless : ^1.6.1
serverless-plugin-aws-alerts: ^2.21.1
For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by adikari** [comment]
@luckynilay did you mean the versions another way around? There is a new release. Can you update to latest and try again?
