### ISSUE TITLE
Unable to install in project that does not use Husky >=5

### ISSUE THREAD

**Issue by Logikgate** [ACloudGuru/serverless-plugin-aws-alerts#176]
# This is a Bug Report

## Description

When installing the latest via npm the install fails with the below message if the project you are trying to install into doesn't use husky >=5.

<img width="731" alt="Screen Shot 2021-05-01 at 10 45 15 AM" src="https://user-images.githubusercontent.com/2379994/116785961-57ba1400-aa6a-11eb-8377-c4f3c4647197.png">

It appears this is coming from the [npm postinstall script](https://github.com/ACloudGuru/serverless-plugin-aws-alerts/blob/e17efd7e1ca03095241e983aa06d96d9c11494c3/package.json#L11) and happens because husky is listed as a devDependency in this project so it doesn't get installed for use by the consuming project.

Could this postInstall script be transitioned to an `npm run prepare` script like the [husky README](https://www.npmjs.com/package/husky) suggests so that projects that use this are not required to have husky >= 5 installed?

If acceptable I'm happy to make the pull request 😄

**Comment by Logikgate** [comment]
Closing, this is a non issue. For some reason npm 7 was complaining about this while trying to upgrade to the latest but after fully uninstalling the package and installing this version the postinstall script doesn't run and all's good

**Comment by mmagyar-seon** [comment]
This is an issue, if you have your .git folder in a different folder then your node js project.
husky should not be included in postinstall script.

**Comment by rachnareddyg** [comment]
This is an issue for me too. I have .git folder in a different folder.

**Comment by deepakthankachan** [comment]
Having this same issue with npm 7

**Comment by akiraah** [comment]
What's the solution for this ?
