### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by johncmckim** [ACloudGuru/serverless-plugin-aws-alerts#20]
CloudWatch alarms support the ability to specify actions to take on missing data. See [the announcement](https://aws.amazon.com/about-aws/whats-new/2017/03/cloudwatch-alarms-releases-two-new-alarm-configuration-settings/). This would be very useful for functions that are not triggered often.

Need to check for cloudformation support.

**Comment by canstudios-louisem** [comment]
Cloudformation supports it, see here http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html#cfn-cloudwatch-alarms-treat-missing-data

**Comment by johncmckim** [comment]
@canstudios-louisem I can't see where that property exists in the documentation. Can you show me an example Alarm in CloudFormation with the property for missing data so I can implement this.

**Comment by canstudios-louisem** [comment]
Apologies i thought i had seen it in the docs apparently it's not in yet see https://forums.aws.amazon.com/thread.jspa?threadID=253193&tstart=0

**Comment by johncmckim** [comment]
Just published a new version
