### ISSUE TITLE
Access additional settings option in the alarms

### ISSUE THREAD

**Issue by suku-h** [ACloudGuru/serverless-plugin-aws-alerts#25]
In cloudwatch while creating an alarm, you can specify that insufficient_data state be treated as good and not send an alarm. 

I would like to make this setting for the alarm: 
[https://imagebin.ca/v/3QUAG0PBtGM3](url)

How can I do this?

**Comment by chrishiste** [comment]
I was looking to do exactly that ! So I wrote a PR, it works you can use it while waiting for the PR to get merged ;)

https://github.com/ACloudGuru/serverless-plugin-aws-alerts/pull/26

Cheers

**Comment by johncmckim** [comment]
Just published a new version
