### ISSUE TITLE
Get ready for the new CloudWatch Dashboards policies

### ISSUE THREAD

**Issue by flpStrri** [ACloudGuru/serverless-plugin-aws-alerts#55]
# This is a Feature Proposal

## Description

For feature proposals:
* I just got an email regarding the new policies for dashboards, we will need to redeploy our serverless with this changes and would be nice update this plugin.

## Attachments
> Hello,
> 
> We are contacting you to let you know that the Amazon CloudWatch Dashboards[1] will be migrating to a new IAM permission policy on April 1, 2018. The new permission policy enables you to restrict and allow access to your dashboards with finer control. You may need to update your current CloudWatch IAM policy for users in your account to continue using dashboards when we migrate to the new permission policy. Please visit the CloudWatch console in any region before April 1, 2018 to check your current permissions and see if any updates are needed. 
> 
> Today, CloudWatch Dashboards use the permissions to PutMetricData and GetMetricData APIs (actions) in an IAM policy for read and write access. A user with PutMetricData permission is allowed to create and delete dashboards while a user with GetMetricData permission is allowed to view individual dashboards as well as the list of dashboards. As you may know, we recently launched four new APIs for Dashboards[2] – PutDashboard, DeleteDashboards, GetDashboard, and ListDashboards – to dynamically build and maintain your dashboards. Starting April 1, 2018, CloudWatch Dashboards will migrate to using the permissions to these four APIs for read and write access. The new permission policy provides you with an improved access control to your dashboards. After the migration you can, for example, restrict a user from deleting any dashboards while having the access to create or view dashboards.
> 
> Please note that if all users in your account have been assigned the “AdministratorAccess” policy, or the “CloudWatchFullAccess” policy or any similar policies that guarantees full access to CloudWatch then you do not need to make any changes. However, if any user in your account does not have such policies that user will not be able to perform part or all the actions available for CloudWatch Dashboards after April 1, 2018. To maintain the current dashboards access control and experience for such users you need to update their IAM policy before April 1, 2018. For example, the IAM policy of a user with GetMetricData permission should be updated to allow GetDashboard and ListDashboards actions. To learn more about this permission policy migration and what updates are needed, please visit here[3].  You will also see this message as a notification in CloudWatch console when you visit next time and an option to check your current dashboards permissions from CloudWatch. 
> 
> If you have any questions, please contact AWS Support[4].
> 
> [1] https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Dashboards.html
> [2] https://aws.amazon.com/blogs/aws/new-api-cloudformation-support-for-amazon-cloudwatch-dashboards/
> [3] https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/dashboard-permissions-update.html
> [4] https://aws.amazon.com/support

**Comment by johncmckim** [comment]
@flpStrri this plugin does not set any IAM roles itself. You are right that the policy that is used in CloudFormation may need to be updated. But I'm unsure what has to be done to this plugin.
