### ISSUE TITLE
Create separate cf template/stack

### ISSUE THREAD

**Issue by kabo** [ACloudGuru/serverless-plugin-aws-alerts#60]
# This is a Feature Proposal

## Description

With this plugin the number of resources in the generated cloudformation template in one of the projects I'm in goes from less than 200 to 322.

It would be great if there was an option to output these resources to another template that could be deployed separately. Or perhaps some other solution.

**Comment by ctg3** [comment]
I had the same issue. I am looking into using this plugin to split the stack: https://github.com/dougmoscrop/serverless-plugin-split-stacks

**Comment by ykravch** [comment]
+1

**Comment by adikari** [comment]
This functionality is added by #127
