### ISSUE TITLE
Questions - Creating Arbitrary Alarms

### ISSUE THREAD

**Issue by devotox** [ACloudGuru/serverless-plugin-aws-alerts#72]
# This is a (Bug Report / Feature Proposal)
This is a question

## Description
Is it possible to use this  module to write arbitrary alarms for other namespaces based on metrics amazon automatically stores i.e. for kinesis and dynamodb as long as the resource is defined in the serverless.yml file

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by martrik** [comment]
It is nearly possible. Have a look at this: https://github.com/ACloudGuru/serverless-plugin-aws-alerts/issues/85#issuecomment-527128810
