### ISSUE TITLE
Support cloudwatch log stream link generation

### ISSUE THREAD

**Issue by fantapop** [ACloudGuru/serverless-plugin-aws-alerts#80]
It would be awesome to add some niceties which are missing from the cloudwatch offering such as ability to fetch specific log lines matching the pattern and dump to a new topic or to generate the log stream link like this repo:

https://github.com/RoundingWellOS/cloudWatchLogsSlackNotification

**Comment by bulkan** [comment]
I'm not sure we want to add more complexity to this plugin giving that we don't have a lot of contributors or maintainers.
