### ISSUE TITLE
Support for SLS version 1.35.1

### ISSUE THREAD

**Issue by airmonitor** [ACloudGuru/serverless-plugin-aws-alerts#82]
npm WARN serverless-plugin-aws-alerts@1.2.4 requires a peer of serverless@^1.12.0 but none is installed. You must install peer dependencies yourself.

+ serverless-plugin-aws-alerts@1.2.4
added 2 packages from 3 contributors in 3.001s

:~$ sls --version
1.35.1

**Comment by bulkan** [comment]
serverless is now at `1.54.0`
