### ISSUE TITLE
Support Alerts for SQS Queue Depth

### ISSUE THREAD

**Issue by anilchinnam** [ACloudGuru/serverless-plugin-aws-alerts#85]
This is a new request to support the alerts for the SQS queue depth. We currently have SQS alerts that we currently configure separately. But, it will be great if we can utilize this plugin for all the alerts like SQS, DynamoDB etc..

**Comment by chrisandrews7** [comment]
Another plugin already exists in the meantime - https://github.com/sbstjn/serverless-sqs-alarms-plugin

**Comment by martrik** [comment]
I feel like SQS alarms could also be created by the plugin if the `FunctionName` dimension wasn't added by default as covered in this [other](https://github.com/ACloudGuru/serverless-plugin-aws-alerts/issues/104) issue. Actually, as far as I can see, this plugin could support any kind of alarm if the issue with the default dimension was fixed. It would be quite cool to have just one serverless plugin to create any kind of alarm.

**Comment by t-zhao** [comment]
While waiting for the [omitDefautlDimension](https://github.com/ACloudGuru/serverless-plugin-aws-alerts/pull/106) PR to be merged, [here](https://github.com/ACloudGuru/serverless-plugin-aws-alerts/pull/106#issuecomment-630365977) is a work-around using [serverless-scriptable-plugin](https://github.com/weixu365/serverless-scriptable-plugin)
