### ISSUE TITLE
Is this plugin still being actively developed?

### ISSUE THREAD

**Issue by kjones** [ACloudGuru/serverless-plugin-aws-alerts#88]
There are so many great questions, bug reports, and pull requests outstanding on this plugin. Is it still actively supported?

**Comment by bulkan** [comment]
Hi all,

Sorry for the late response. We will be looking at all open issues & PR's now.

Can you please list your top 3 issues that we should begin looking at ?

**Comment by kjones** [comment]
Excellent news!

Here's my take on priorities based on what I've come across while using the plugin.
1. Changes that support configuring the full range of [CloudWatch Alarm Properties](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html).
#87,#89
2. Additional ways to specify the alarm SNS topics. e.g. ImportValue, etc.
#76, #77, #90, #91
3. More control over topic naming.
#17, #42

I'm not saying that these specific pull requests are the answer, but that the ideas behind them should be considered when solving for the general categories I've listed.

**Comment by bulkan** [comment]
@kjones thank you for that list we'll prioritize those PR's first.

**Comment by bulkan** [comment]
I think it's a good time to push out a new release to `npm` as I've merged a few PR's (#77, #83, #84, #87).

I'll also be closing this PR if you guys don't mind 😄

**Comment by bulkan** [comment]
@kjones @Limess @Bhuser I've published (1.3.1)[https://www.npmjs.com/package/serverless-plugin-aws-alerts) to npm now

**Comment by kamzil** [comment]
@bulkan I can see that #90 was still left open. Any reason why? The merged PR only considers the special case of Fn::ImportValue. #90 is to allow a more generic case of resolving the ARN via object, e.g. Fn::Join instead of a plain string. At least that was not possible during the creation of that PR.

**Comment by bulkan** [comment]
@kamzil I don’t remember why it was left open and I don’t maintain this repo anymore.

**Comment by kamzil** [comment]
Thanks for a quick reply! Do you know if anyone is currently maintaining this?

**Comment by adikari** [comment]
> Thanks for a quick reply! Do you know if anyone is currently maintaining this?

I am volunteering to maintain this repository. It might be a slow start though.
